function f_sym = Fn_SLPIAHDR_ode(in1,in2,TrRate,ImGainRate,ImLossRate)
%Fn_SLPIAHDR_ode
%    F_SYM = Fn_SLPIAHDR_ode(IN1,IN2,TrRate,ImGainRate,ImLossRate)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Feb-2024 11:54:52

A = in1(5,:);
H = in1(6,:);
I = in1(4,:);
L = in1(2,:);
P = in1(3,:);
R = in1(8,:);
S = in1(1,:);
pD = in2(9,:);
pH = in2(8,:);
pI = in2(7,:);
qA = in2(6,:);
tauA = in2(3,:);
tauH = in2(5,:);
tauI = in2(4,:);
tauL = in2(1,:);
tauP = in2(2,:);
t2 = A.*qA;
t3 = A.*tauA;
t4 = L.*tauL;
t5 = ImLossRate.*R;
t6 = ImGainRate.*S;
t7 = H./1.0e+1;
t8 = I+P+t2+t7;
t9 = (S.*TrRate.*t8)./1.795e+5;
f_sym = [t5-t6-t9;-t4+t9;t4-P.*tauP;-I.*tauI+P.*pI.*tauP;-t3-P.*tauP.*(pI-1.0);-H.*tauH+I.*pH.*tauI;H.*pD.*tauH;t3-t5+t6-H.*tauH.*(pD-1.0)-I.*tauI.*(pH-1.0)];
end
