function h_sym = Fn_SLPIAHDR_out(in1,in2,TrRate)
%Fn_SLPIAHDR_out
%    H_SYM = Fn_SLPIAHDR_out(IN1,IN2,TrRate)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Feb-2024 11:54:53

A = in1(5,:);
H = in1(6,:);
I = in1(4,:);
L = in1(2,:);
P = in1(3,:);
S = in1(1,:);
pI = in2(7,:);
qA = in2(6,:);
tauA = in2(3,:);
tauI = in2(4,:);
tauP = in2(2,:);
t2 = pI-1.0;
t3 = 1.0./tauA;
t4 = 1.0./tauI;
t5 = 1.0./tauP;
t6 = pI.*t4;
t7 = qA.*t2.*t3;
t8 = -t7;
t9 = t5+t6+t8;
h_sym = [A+H+I+L+P;(S.*TrRate.*(I+P+A.*qA))./1.795e+5;TrRate.*t9;(S.*TrRate.*t9)./1.795e+5];
end
