FROM khbence/covid_ppcu:base_cpu as builder

RUN mkdir -p /workdir
COPY cxxopts /workdir/cxxopts
COPY rapidjson /workdir/rapidjson
COPY thrust /workdir/thrust
COPY cub /workdir/cub
COPY cmake /workdir/cmake
COPY include /workdir/include
COPY src /workdir/src
COPY Makefile /workdir/
COPY CMakeLists.txt /workdir/

WORKDIR /workdir
RUN make buildCPU

FROM ubuntu
RUN apt update
RUN apt-get install -y g++
COPY --from=builder /workdir/build/panSim .
ENTRYPOINT [ "./panSim" ]