function f_sym = Fn_SLPIA_ode(in1,in2,TrRate,ImGainRate)
%Fn_SLPIA_ode
%    F_SYM = Fn_SLPIA_ode(IN1,IN2,TrRate,ImGainRate)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-Feb-2024 22:36:22

A = in1(5,:);
I = in1(4,:);
L = in1(2,:);
P = in1(3,:);
S = in1(1,:);
alpha = in2(1,:);
delta = in2(6,:);
gamma = in2(7,:);
rhoA = in2(3,:);
rhoI = in2(4,:);
zeta = in2(2,:);
t2 = A.*delta;
t3 = L.*alpha;
t4 = I+P+t2;
t5 = (S.*TrRate.*t4)./1.795e+5;
f_sym = [-t5-ImGainRate.*S;-t3+t5;t3-P.*zeta;-I.*rhoI+P.*gamma.*zeta;-A.*rhoA-P.*zeta.*(gamma-1.0)];
end
