function p = fpar_proba(pars,M0,M1,M2,M3,P0,P1,P2,P3,P4,x)
%%
%  This is a simple selector function generated from CasADi Function.
%  
%  File: fpar_proba.m
%  Directory: /home/ppolcz/_/5_Sztaki20_Main/Utils/casadi_helper/Sandbox
%  Author: Peter Polcz (ppolcz@gmail.com) 
%  Generated by function `pcas_gen_mfun_vectsel`
%  Generated on 2021. November 03. (2021b)
%

arguments
    pars (9,1) = zeros(9,1)
    M0 (2,3) = zeros(2,3)
    M1 (2,3) = zeros(2,3)
    M2 (2,3) = zeros(2,3)
    M3 (2,3) = zeros(2,3)
    P0 (3,3) = zeros(3,3)
    P1 (3,3) = zeros(3,3)
    P2 (3,3) = zeros(3,3)
    P3 (3,3) = zeros(3,3)
    P4 (3,3) = zeros(3,3)
    x (3,5) = zeros(3,5)
end

p = zeros(78,1);

p(1) = pars(1);
p(2) = pars(2);
p(3) = pars(3);
p(4) = pars(4);
p(5) = pars(5);
p(6) = pars(6);
p(7) = pars(7);
p(8) = pars(8);
p(9) = pars(9);
p(10) = M0(1);
p(11) = M0(2);
p(12) = M0(3);
p(13) = M0(4);
p(14) = M0(5);
p(15) = M0(6);
p(16) = M1(1);
p(17) = M1(2);
p(18) = M1(3);
p(19) = M1(4);
p(20) = M1(5);
p(21) = M1(6);
p(22) = M2(1);
p(23) = M2(2);
p(24) = M2(3);
p(25) = M2(4);
p(26) = M2(5);
p(27) = M2(6);
p(28) = M3(1);
p(29) = M3(2);
p(30) = M3(3);
p(31) = M3(4);
p(32) = M3(5);
p(33) = M3(6);
p(34) = P0(1);
p(35) = P0(2);
p(36) = P0(3);
p(37) = P0(5);
p(38) = P0(6);
p(39) = P0(9);
p(40) = P1(1);
p(41) = P1(2);
p(42) = P1(3);
p(43) = P1(5);
p(44) = P1(6);
p(45) = P1(9);
p(46) = P2(1);
p(47) = P2(2);
p(48) = P2(3);
p(49) = P2(5);
p(50) = P2(6);
p(51) = P2(9);
p(52) = P3(1);
p(53) = P3(2);
p(54) = P3(3);
p(55) = P3(5);
p(56) = P3(6);
p(57) = P3(9);
p(58) = P4(1);
p(59) = P4(2);
p(60) = P4(3);
p(61) = P4(5);
p(62) = P4(6);
p(63) = P4(9);
p(64) = x(1);
p(65) = x(2);
p(66) = x(3);
p(67) = x(4);
p(68) = x(5);
p(69) = x(6);
p(70) = x(7);
p(71) = x(8);
p(72) = x(9);
p(73) = x(10);
p(74) = x(11);
p(75) = x(12);
p(76) = x(13);
p(77) = x(14);
p(78) = x(15);

end
