function x = fvar_proba(var_array,var_veccell0,var_veccell1,var_veccell2,var_veccell3,var_matcell0,var_matcell1,var_symcell0,var_symcell1,var_symcell2,var_blksym,var_blksymcell0,var_blksymcell1)
%%
%  This is a simple selector function generated from CasADi Function.
%  
%  File: fvar_proba.m
%  Directory: /home/ppolcz/_/5_Sztaki20_Main/Utils/casadi_helper/Sandbox
%  Author: Peter Polcz (ppolcz@gmail.com) 
%  Generated by function `pcas_gen_mfun_vectsel`
%  Generated on 2021. November 03. (2021b)
%

arguments
    var_array (2,3) = zeros(2,3)
    var_veccell0 (3,1) = zeros(3,1)
    var_veccell1 (3,1) = zeros(3,1)
    var_veccell2 (3,1) = zeros(3,1)
    var_veccell3 (3,1) = zeros(3,1)
    var_matcell0 (2,3) = zeros(2,3)
    var_matcell1 (2,3) = zeros(2,3)
    var_symcell0 (2,2) = zeros(2,2)
    var_symcell1 (2,2) = zeros(2,2)
    var_symcell2 (2,2) = zeros(2,2)
    var_blksym (9,9) = zeros(9,9)
    var_blksymcell0 (4,4) = zeros(4,4)
    var_blksymcell1 (4,4) = zeros(4,4)
end

x = zeros(68,1);

x(1) = var_array(1);
x(2) = var_array(2);
x(3) = var_array(3);
x(4) = var_array(4);
x(5) = var_array(5);
x(6) = var_array(6);
x(7) = var_veccell0(1);
x(8) = var_veccell0(2);
x(9) = var_veccell0(3);
x(10) = var_veccell1(1);
x(11) = var_veccell1(2);
x(12) = var_veccell1(3);
x(13) = var_veccell2(1);
x(14) = var_veccell2(2);
x(15) = var_veccell2(3);
x(16) = var_veccell3(1);
x(17) = var_veccell3(2);
x(18) = var_veccell3(3);
x(19) = var_matcell0(1);
x(20) = var_matcell0(2);
x(21) = var_matcell0(3);
x(22) = var_matcell0(4);
x(23) = var_matcell0(5);
x(24) = var_matcell0(6);
x(25) = var_matcell1(1);
x(26) = var_matcell1(2);
x(27) = var_matcell1(3);
x(28) = var_matcell1(4);
x(29) = var_matcell1(5);
x(30) = var_matcell1(6);
x(31) = var_symcell0(1);
x(32) = var_symcell0(2);
x(33) = var_symcell0(4);
x(34) = var_symcell1(1);
x(35) = var_symcell1(2);
x(36) = var_symcell1(4);
x(37) = var_symcell2(1);
x(38) = var_symcell2(2);
x(39) = var_symcell2(4);
x(40) = var_blksym(1);
x(41) = var_blksym(2);
x(42) = var_blksym(11);
x(43) = var_blksym(21);
x(44) = var_blksym(22);
x(45) = var_blksym(23);
x(46) = var_blksym(31);
x(47) = var_blksym(32);
x(48) = var_blksym(41);
x(49) = var_blksym(51);
x(50) = var_blksym(52);
x(51) = var_blksym(53);
x(52) = var_blksym(54);
x(53) = var_blksym(61);
x(54) = var_blksym(62);
x(55) = var_blksym(63);
x(56) = var_blksym(71);
x(57) = var_blksym(72);
x(58) = var_blksym(81);
x(59) = var_blksymcell0(1);
x(60) = var_blksymcell0(6);
x(61) = var_blksymcell0(11);
x(62) = var_blksymcell0(12);
x(63) = var_blksymcell0(16);
x(64) = var_blksymcell1(1);
x(65) = var_blksymcell1(6);
x(66) = var_blksymcell1(11);
x(67) = var_blksymcell1(12);
x(68) = var_blksymcell1(16);

end
