FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y g++ cmake make git
RUN apt -y install build-essential libssl-dev wget
RUN wget https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3.tar.gz
RUN tar -zxvf cmake-3.21.3.tar.gz
WORKDIR /cmake-3.21.3
RUN ./bootstrap
RUN make
RUN make install
WORKDIR /
RUN rm -rf /cmake-3.21.3

RUN useradd -m -d /home/nonroot -u 1000 nonroot && chown -R nonroot /home/nonroot
USER nonroot