function PanSim_args = load_PanSim_args(Config,args)
arguments
    Config string {mustBeMember(Config, ...
        ["Free","Real","Delay7","Delay14","Delay21","Omicron","Scenario1","Manual"])} = "Free"
    args.InfectiousnessMultiplier (1,7) = [0.98,1.81,2.11,2.58,4.32,6.8,6.8];
    args.DiseaseProgressionScaling (1,7) = [0.94,1.03,0.813,0.72,0.57,0.463,0.45];
    args.Closures string = "emptybbRules.json";
end

str = sprintf('%g,',args.InfectiousnessMultiplier);
args.InfectiousnessMultiplier = string(str(1:end-1));

str = sprintf('%g,',args.DiseaseProgressionScaling);
args.DiseaseProgressionScaling = string(str(1:end-1));

switch Config
    case "Manual"

        PanSim_args = [
            "panSim", "-r", " ", ...
             "--quarantinePolicy", "0", ...
             "-k", "0.00041", ...
             "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "--closures", "inputConfigFiles/" + args.Closures, ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", args.InfectiousnessMultiplier, ...
             "--diseaseProgressionScaling", args.DiseaseProgressionScaling
             ];

    case "Free"

        PanSim_args = [
            "panSim", "-r", " ", ...
             "--quarantinePolicy", "0", ...
             "-k", "0.00041", ...
             "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "--closures", "inputConfigFiles/emptybbRules.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
"--infectiousnessMultiplier",  "0.98,1.81,2.110,2.58,4.32,6.800,6.80", ...
"--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45"
...                             Wild            |    Omicron BA.5           
...                                  Alpha      |         Omicron BQ.1       
...                                       Delta |               Omicron XBB 
...                                             Omicron BA.1,2  
             ];

    case "Scenario1"

        PanSim_args = [
            "panSim", "-r", " ", ...
             "--quarantinePolicy", "0", ...
             "-k", "0.00041", ...
             "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "--closures", "inputConfigFiles/Scenario1.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,1.81,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45"
             ];

    case "Real"

        PanSim_args = [
            "panSim", "-r", " ", ...
            "--quarantinePolicy", "3", ...
            "-k", "0.00041", ...     
            "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,1.81,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45", ... 
             "--closures","inputConfigFiles/closureJun6_real_later3_delta_omicronBA2_earlier8.json"
             ];

    case "Delay21"

        PanSim_args = [
            "panSim", "-r", " ", ...
            "--quarantinePolicy", "3", ...
            "-k", "0.00041", ...     
            "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,1.81,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45", ... 
             "--closures","inputConfigFiles/closureJun6_real_later3_delta_omicronBA2_earlier8_Delay21.json"
             ];

    case "Omicron"

        PanSim_args = [
            "panSim", "-r", " ", ...
            "--quarantinePolicy", "0", ...
            "-k", "0.00041", ...
             "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "--closures", "inputConfigFiles/Scenario1.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,3.6,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,0.46,0.813,0.72,0.57,0.463,0.45"];

end

end