function PanSim_args = load_PanSim_args(Config)
arguments
    Config string {mustBeMember(Config,["Free","Real","Delay7","Delay14","Delay21"])} = "Free"
end

switch Config
    case "Free"

        PanSim_args = [
            "panSim", "-r", " ", ...
             "--quarantinePolicy", "0", ...
             "-k", "0.00041", ...
             "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "--closures", "inputConfigFiles/emptybbRules.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,1.81,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45"
             ];

    case "Real"

        PanSim_args = [
            "panSim", "-r", " ", ...
            "--quarantinePolicy", "3", ...
            "-k", "0.00041", ...     
            "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,1.81,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45", ... 
             "--closures","inputConfigFiles/closureJun6_real_later3_delta_omicronBA2_earlier8.json"
             ];

    case "Delay21"

        PanSim_args = [
            "panSim", "-r", " ", ...
            "--quarantinePolicy", "3", ...
            "-k", "0.00041", ...     
            "--progression", "inputConfigFiles/progressions_Jun17_tune/transition_config.json", ...
             "-A", "inputConfigFiles/agentTypes_3.json", ...
             "-a", "inputRealExample/agents1.json", ...
             "-l", "inputRealExample/locations0.json", ...
             "--infectiousnessMultiplier", "0.98,1.81,2.11,2.58,4.32,6.8,6.8", ...
             "--diseaseProgressionScaling", "0.94,1.03,0.813,0.72,0.57,0.463,0.45", ... 
             "--closures","inputConfigFiles/closureJun6_real_later3_delta_omicronBA2_earlier8_Delay21.json"
             ];

end

end