function h_sym = Fn_SLPIA_out(in1,in2,TrRate)
%Fn_SLPIA_out
%    H_SYM = Fn_SLPIA_out(IN1,IN2,TrRate)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    19-Jan-2024 15:17:27

A = in1(5,:);
I = in1(4,:);
L = in1(2,:);
P = in1(3,:);
S = in1(1,:);
delta = in2(6,:);
gamma = in2(7,:);
rhoA = in2(3,:);
rhoI = in2(4,:);
zeta = in2(2,:);
t2 = gamma-1.0;
t3 = 1.0./rhoA;
t4 = 1.0./rhoI;
t5 = 1.0./zeta;
t6 = gamma.*t4;
t7 = delta.*t2.*t3;
t8 = -t7;
t9 = t5+t6+t8;
h_sym = [A+I+L+P;(S.*TrRate.*(I+P+A.*delta))./1.795e+5;TrRate.*t9;(S.*TrRate.*t9)./1.795e+5];
end
